/**
 * Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved.
 *
 * @generated SignedSource<<227d83cd3e8798dc748903eca29bd628>>
 *
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * !! This file is generated by generate_fbt_number_consistency.php !!
 * !! Do not modify it manually                                     !!
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 */
var FbtNumberConsistency = {
    "dataModuleNames": [
        "TestData_IntlCLDRNumberType01",
        "TestData_IntlCLDRNumberType02",
        "TestData_IntlCLDRNumberType03",
        "TestData_IntlCLDRNumberType04",
        "TestData_IntlCLDRNumberType05",
        "TestData_IntlCLDRNumberType06",
        "TestData_IntlCLDRNumberType07",
        "TestData_IntlCLDRNumberType08",
        "TestData_IntlCLDRNumberType09",
        "TestData_IntlCLDRNumberType10",
        "TestData_IntlCLDRNumberType11",
        "TestData_IntlCLDRNumberType12",
        "TestData_IntlCLDRNumberType13",
        "TestData_IntlCLDRNumberType14",
        "TestData_IntlCLDRNumberType15",
        "TestData_IntlCLDRNumberType16",
        "TestData_IntlCLDRNumberType17",
        "TestData_IntlCLDRNumberType18",
        "TestData_IntlCLDRNumberType19",
        "TestData_IntlCLDRNumberType20",
        "TestData_IntlCLDRNumberType21",
        "TestData_IntlCLDRNumberType22",
        "TestData_IntlCLDRNumberType23",
        "TestData_IntlCLDRNumberType24",
        "TestData_IntlCLDRNumberType25",
        "TestData_IntlCLDRNumberType26",
        "TestData_IntlCLDRNumberType27",
        "TestData_IntlCLDRNumberType28",
        "TestData_IntlCLDRNumberType29",
        "TestData_IntlCLDRNumberType30",
        "TestData_IntlCLDRNumberType31",
        "TestData_IntlCLDRNumberType32",
        "TestData_IntlCLDRNumberType33",
        "TestData_IntlCLDRNumberType34",
        "TestData_IntlCLDRNumberType35",
        "TestData_IntlCLDRNumberType36",
        "TestData_IntlCLDRNumberType37",
        "TestData_IntlCLDRNumberType38",
        "TestData_IntlCLDRNumberType39",
        "TestData_IntlCLDRNumberType40",
        "TestData_IntlCLDRNumberType41",
        "TestData_IntlCLDRNumberType42",
        "TestData_IntlCLDRNumberType43",
        "TestData_IntlCLDRNumberType44",
        "TestData_IntlCLDRNumberType45",
        "TestData_IntlCLDRNumberType46"
    ]
};
module.exports = FbtNumberConsistency;
