language: node_js

node_js:
  - '10.4.0'
  - '12'

branches:
  only:
    - master

env:
  - CMD=demo-app:test
  - CMD=fb-tiger-hash:test
  - CMD=babel-plugin-fbt-runtime:test
  - CMD=babel-plugin-fbt:test

script: yarn run "$CMD"

jobs:
  include:
    - stage: test
      name: "Flow checks - node v10.4.0"
      node_js: '10.4.0'
      script: yarn flow:check
    - name: "Flow checks - node v12"
      node_js: '12'
      script: yarn flow:check

before_install:
  # Install latest yarn (will go to ~/.yarn) and update $PATH for current shell
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
