/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<3e1fa5cc722daed56f7b3beb51a9dff8>>
 *
 * Generated by CLDRGenScript
 *
 * @flow
 */
const IntlCLDRNumberType40 = {
  getNumberVariations: function() {
    return [4,8,24];
  },

  getFallback: function() {
    return 24;
  }

};

module.exports = IntlCLDRNumberType40;
