/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<57fe889ec0e4d7de3517c74027884981>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow
 */
const IntlCLDRNumberType12 = {
  getNumberVariations: function() {
    return [4,24];
  },

  getFallback: function() {
    return 24;
  }

};

module.exports = IntlCLDRNumberType12;
