/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<188362aa0b7dd671d967a3a71d35d454>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow
 */
const IntlCLDRNumberType42 = {
  getNumberVariations: function() {
    return [24];
  },

  getFallback: function() {
    return 24;
  }

};

module.exports = IntlCLDRNumberType42;
