/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<77f4490b88c4a5b093f2b29f33bcc867>>
 *
 * Generated by CLDRGenScript
 *
 * @flow
 */
const IntlCLDRNumberType19 = {
  getNumberVariations: function() {
    return [4,20,24];
  },

  getFallback: function() {
    return 24;
  }

};

module.exports = IntlCLDRNumberType19;
