/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<3d25c9aa185da030393b8d0f8e5686b9>>
 *
 * Generated by CLDRGenScript
 *
 * @flow
 */
const IntlCLDRNumberType42 = {
  getNumberVariations: function() {
    return [24];
  },

  getFallback: function() {
    return 24;
  }

};

module.exports = IntlCLDRNumberType42;
