/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<31fdc94051ba728d69e3c6a9a82c9f9b>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow
 */
const IntlCLDRNumberType46 = {
  getNumberVariations: function() {
    return [4,20,24];
  },

  getFallback: function() {
    return 24;
  }

};

module.exports = IntlCLDRNumberType46;
