/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<aaceb2c025fb0d39f0dd92e655edcaaa>>
 *
 * Generated by CLDRGenScript
 *
 * @flow
 */
const IntlCLDRNumberType30 = {
  getNumberVariations: function() {
    return [4,20,12,24];
  },

  getFallback: function() {
    return 12;
  }

};

module.exports = IntlCLDRNumberType30;
