/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<c55e28ae06146ddfb2475f2f7f593228>>
 *
 * Generated by CLDRGenScript
 *
 * @flow
 */
const IntlCLDRNumberType24 = {
  getNumberVariations: function() {
    return [4,8,12,24];
  },

  getFallback: function() {
    return 24;
  }

};

module.exports = IntlCLDRNumberType24;
