/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<9f41bfec807e40f9bcc7fbfc23798985>>
 *
 * Generated by CLDRGenScript
 *
 * @flow
 */
const IntlCLDRNumberType46 = {
  getNumberVariations: function() {
    return [4,20,24];
  },

  getFallback: function() {
    return 24;
  }

};

module.exports = IntlCLDRNumberType46;
