/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<18ab25b87fffe34731938886192e77b6>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow
 */
const IntlCLDRNumberType29 = {
  getNumberVariations: function() {
    return [4,20,12,24];
  },

  getFallback: function() {
    return 24;
  }

};

module.exports = IntlCLDRNumberType29;
