/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<920cbc067f445daf19a7db6f8c0334d7>>
 *
 * Generated by CLDRGenScript
 *
 * @flow
 */
const IntlCLDRNumberType38 = {
  getNumberVariations: function() {
    return [4,24];
  },

  getFallback: function() {
    return 24;
  }

};

module.exports = IntlCLDRNumberType38;
