/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<4a4d9c07281aa2e33cee7f132a1291d7>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow
 */
const IntlCLDRNumberType39 = {
  getNumberVariations: function() {
    return [24];
  },

  getFallback: function() {
    return 24;
  }

};

module.exports = IntlCLDRNumberType39;
