/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<83ebe46502c0edfda41a6773296a1161>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow
 */
const IntlCLDRNumberType01 = {
  getNumberVariations: function() {
    return [24];
  },

  getFallback: function() {
    return 24;
  }

};

module.exports = IntlCLDRNumberType01;
