/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<a81e692f6ab9b36a08bc459543bbe484>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow
 */
const IntlCLDRNumberType37 = {
  getNumberVariations: function() {
    return [4,24];
  },

  getFallback: function() {
    return 24;
  }

};

module.exports = IntlCLDRNumberType37;
