/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<8bd229b87a2f0220c410f78f3ba7d9a1>>
 *
 * @flow strict
 * Generated by JSModulesToClientScript
 */

// flowlint implicit-inexact-object:error

'use strict';

export type GenderConstEnum = $GenderConstEnum;

const GenderConst = Object.freeze({
  /* eslint-disable fb-www/no-flowfixme-in-flow-strict */
  NOT_A_PERSON: ((0: $FlowFixMe): GenderConstEnum),
  FEMALE_SINGULAR: ((1: $FlowFixMe): GenderConstEnum),
  MALE_SINGULAR: ((2: $FlowFixMe): GenderConstEnum),
  FEMALE_SINGULAR_GUESS: ((3: $FlowFixMe): GenderConstEnum),
  MALE_SINGULAR_GUESS: ((4: $FlowFixMe): GenderConstEnum),
  MIXED_SINGULAR: ((5: $FlowFixMe): GenderConstEnum),
  MIXED_PLURAL: ((5: $FlowFixMe): GenderConstEnum),
  NEUTER_SINGULAR: ((6: $FlowFixMe): GenderConstEnum),
  UNKNOWN_SINGULAR: ((7: $FlowFixMe): GenderConstEnum),
  FEMALE_PLURAL: ((8: $FlowFixMe): GenderConstEnum),
  MALE_PLURAL: ((9: $FlowFixMe): GenderConstEnum),
  NEUTER_PLURAL: ((10: $FlowFixMe): GenderConstEnum),
  UNKNOWN_PLURAL: ((11: $FlowFixMe): GenderConstEnum),
  /* eslint-enable fb-www/no-flowfixme-in-flow-strict */
});

module.exports = GenderConst;
