/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<c3119c97b60085d1b8cc97e7e3c4d420>>
 *
 * @flow strict
 * Generated by JSModulesToClientScript
 */

// flowlint implicit-inexact-object:error

'use strict';

export type GenderConstEnum = $GenderConstEnum;

const GenderConst = Object.freeze({
  /* eslint-disable fb-www/no-flowfixme-in-flow-strict */
  NOT_A_PERSON: ((0: $FlowFixMe): GenderConstEnum),
  UNKNOWN_SINGULAR: ((1: $FlowFixMe): GenderConstEnum),
  UNKNOWN_PLURAL: ((2: $FlowFixMe): GenderConstEnum),
  MALE: ((3: $FlowFixMe): GenderConstEnum),
  FEMALE: ((4: $FlowFixMe): GenderConstEnum),
  /* eslint-enable fb-www/no-flowfixme-in-flow-strict */
});

module.exports = GenderConst;
