/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<95946ce56401e86d9907f98de5556ac9>>
 *
 * Generated by JSModulesToClientScript
 */
const GenderConst {
    "NOT_A_PERSON": 0,
    "FEMALE_SINGULAR": 1,
    "MALE_SINGULAR": 2,
    "FEMALE_SINGULAR_GUESS": 3,
    "MALE_SINGULAR_GUESS": 4,
    "MIXED_SINGULAR": 5,
    "MIXED_PLURAL": 5,
    "NEUTER_SINGULAR": 6,
    "UNKNOWN_SINGULAR": 7,
    "FEMALE_PLURAL": 8,
    "MALE_PLURAL": 9,
    "NEUTER_PLURAL": 10,
    "UNKNOWN_PLURAL": 11
};

module.exports = GenderConst;
