/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<3088b8de4034081ac5c71a232624e6ec>>
 *
 * Generated by JSModulesToClientScript
 */

const DEFAULT_CONFIG = {
    "decimalSeparator": ".",
    "numberDelimiter": ",",
    "minDigitsForThousandsSeparator": 0,
    "standardDecimalPatternInfo": {
        "primaryGroupSize": 3,
        "secondaryGroupSize": 3
    },
    "numberingSystemData": null
};
const localeToConfig = {
    "en_US": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "ca_ES": {
        "decimalSeparator": ",",
        "numberDelimiter": "\u00a0",
        "minDigitsForThousandsSeparator": 5,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "cs_CZ": {
        "decimalSeparator": ",",
        "numberDelimiter": "\u00a0",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "cx_PH": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "cy_GB": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "da_DK": {
        "decimalSeparator": ",",
        "numberDelimiter": ".",
        "minDigitsForThousandsSeparator": 5,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "de_DE": {
        "decimalSeparator": ",",
        "numberDelimiter": ".",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "eu_ES": {
        "decimalSeparator": ",",
        "numberDelimiter": ".",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "en_PI": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "en_UD": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "en_OP": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "ck_US": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "es_LA": {
        "decimalSeparator": ",",
        "numberDelimiter": ".",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "es_CL": {
        "decimalSeparator": ",",
        "numberDelimiter": ".",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "es_CO": {
        "decimalSeparator": ",",
        "numberDelimiter": ".",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "es_ES": {
        "decimalSeparator": ",",
        "numberDelimiter": "\u00a0",
        "minDigitsForThousandsSeparator": 5,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "es_MX": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "es_VE": {
        "decimalSeparator": ",",
        "numberDelimiter": ".",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "gn_PY": {
        "decimalSeparator": ",",
        "numberDelimiter": ".",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "fb_AA": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "fb_AC": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "fb_HA": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "fb_AR": {
        "decimalSeparator": "\u066b",
        "numberDelimiter": "\u066c",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": {
            "digits": "\u0660\u0661\u0662\u0663\u0664\u0665\u0666\u0667\u0668\u0669"
        }
    },
    "fb_HX": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "fb_LS": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "fb_LL": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "fb_RL": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "fb_ZH": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "fi_FI": {
        "decimalSeparator": ",",
        "numberDelimiter": "\u00a0",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "fr_FR": {
        "decimalSeparator": ",",
        "numberDelimiter": "\u00a0",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "gl_ES": {
        "decimalSeparator": ",",
        "numberDelimiter": ".",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "ht_HT": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "hu_HU": {
        "decimalSeparator": ",",
        "numberDelimiter": "\u00a0",
        "minDigitsForThousandsSeparator": 5,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "it_IT": {
        "decimalSeparator": ",",
        "numberDelimiter": ".",
        "minDigitsForThousandsSeparator": 5,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "ja_JP": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "ko_KR": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "nb_NO": {
        "decimalSeparator": ",",
        "numberDelimiter": "\u00a0",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "nn_NO": {
        "decimalSeparator": ",",
        "numberDelimiter": "\u00a0",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "nl_NL": {
        "decimalSeparator": ",",
        "numberDelimiter": ".",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "fy_NL": {
        "decimalSeparator": ",",
        "numberDelimiter": ".",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "pl_PL": {
        "decimalSeparator": ",",
        "numberDelimiter": "\u00a0",
        "minDigitsForThousandsSeparator": 5,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "pt_BR": {
        "decimalSeparator": ",",
        "numberDelimiter": ".",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "pt_PT": {
        "decimalSeparator": ",",
        "numberDelimiter": "\u00a0",
        "minDigitsForThousandsSeparator": 5,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "ro_RO": {
        "decimalSeparator": ",",
        "numberDelimiter": ".",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "ru_RU": {
        "decimalSeparator": ",",
        "numberDelimiter": "\u00a0",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "sk_SK": {
        "decimalSeparator": ",",
        "numberDelimiter": "\u00a0",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "sl_SI": {
        "decimalSeparator": ",",
        "numberDelimiter": ".",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "sv_SE": {
        "decimalSeparator": ",",
        "numberDelimiter": "\u00a0",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "th_TH": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "tr_TR": {
        "decimalSeparator": ",",
        "numberDelimiter": ".",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "ku_TR": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "zh_CN": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "zh_HK": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "zh_TW": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "fb_LT": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "af_ZA": {
        "decimalSeparator": ",",
        "numberDelimiter": "\u00a0",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "sq_AL": {
        "decimalSeparator": ",",
        "numberDelimiter": "\u00a0",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "hy_AM": {
        "decimalSeparator": ",",
        "numberDelimiter": "\u00a0",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "az_AZ": {
        "decimalSeparator": ",",
        "numberDelimiter": ".",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "be_BY": {
        "decimalSeparator": ",",
        "numberDelimiter": "\u00a0",
        "minDigitsForThousandsSeparator": 5,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "bn_IN": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 2
        },
        "numberingSystemData": null
    },
    "bs_BA": {
        "decimalSeparator": ",",
        "numberDelimiter": ".",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "bg_BG": {
        "decimalSeparator": ",",
        "numberDelimiter": "\u00a0",
        "minDigitsForThousandsSeparator": 5,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "hr_HR": {
        "decimalSeparator": ",",
        "numberDelimiter": ".",
        "minDigitsForThousandsSeparator": 5,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "nl_BE": {
        "decimalSeparator": ",",
        "numberDelimiter": ".",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "en_GB": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "en_IN": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 2
        },
        "numberingSystemData": null
    },
    "eo_EO": {
        "decimalSeparator": ",",
        "numberDelimiter": "\u00a0",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "et_EE": {
        "decimalSeparator": ",",
        "numberDelimiter": "\u00a0",
        "minDigitsForThousandsSeparator": 5,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "fo_FO": {
        "decimalSeparator": ",",
        "numberDelimiter": ".",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "fr_CA": {
        "decimalSeparator": ",",
        "numberDelimiter": "\u00a0",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "ka_GE": {
        "decimalSeparator": ",",
        "numberDelimiter": "\u00a0",
        "minDigitsForThousandsSeparator": 5,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "el_GR": {
        "decimalSeparator": ",",
        "numberDelimiter": ".",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "gu_IN": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 2
        },
        "numberingSystemData": null
    },
    "hi_IN": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 2
        },
        "numberingSystemData": null
    },
    "is_IS": {
        "decimalSeparator": ",",
        "numberDelimiter": ".",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "id_ID": {
        "decimalSeparator": ",",
        "numberDelimiter": ".",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "ga_IE": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "jv_ID": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "kn_IN": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "kk_KZ": {
        "decimalSeparator": ",",
        "numberDelimiter": "\u00a0",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "ky_KG": {
        "decimalSeparator": ",",
        "numberDelimiter": "\u00a0",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "la_VA": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "lv_LV": {
        "decimalSeparator": ",",
        "numberDelimiter": "\u00a0",
        "minDigitsForThousandsSeparator": 5,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "li_NL": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "lt_LT": {
        "decimalSeparator": ",",
        "numberDelimiter": "\u00a0",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "mi_NZ": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "mk_MK": {
        "decimalSeparator": ",",
        "numberDelimiter": ".",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "mg_MG": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "ms_MY": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "mt_MT": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "mr_IN": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 2
        },
        "numberingSystemData": {
            "digits": "\u0966\u0967\u0968\u0969\u096a\u096b\u096c\u096d\u096e\u096f"
        }
    },
    "mn_MN": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "ne_NP": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": {
            "digits": "\u0966\u0967\u0968\u0969\u096a\u096b\u096c\u096d\u096e\u096f"
        }
    },
    "pa_IN": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 2
        },
        "numberingSystemData": null
    },
    "rm_CH": {
        "decimalSeparator": ".",
        "numberDelimiter": "\u2019",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "sa_IN": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "sr_RS": {
        "decimalSeparator": ",",
        "numberDelimiter": ".",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "so_SO": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "sw_KE": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "tl_PH": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "ta_IN": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 2
        },
        "numberingSystemData": null
    },
    "tt_RU": {
        "decimalSeparator": ",",
        "numberDelimiter": "\u00a0",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "te_IN": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 2
        },
        "numberingSystemData": null
    },
    "ml_IN": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 2
        },
        "numberingSystemData": null
    },
    "uk_UA": {
        "decimalSeparator": ",",
        "numberDelimiter": "\u00a0",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "uz_UZ": {
        "decimalSeparator": ",",
        "numberDelimiter": "\u00a0",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "vi_VN": {
        "decimalSeparator": ",",
        "numberDelimiter": ".",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "xh_ZA": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "zu_ZA": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "km_KH": {
        "decimalSeparator": ",",
        "numberDelimiter": ".",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "tg_TJ": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "ar_AR": {
        "decimalSeparator": "\u066b",
        "numberDelimiter": "\u066c",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": {
            "digits": "\u0660\u0661\u0662\u0663\u0664\u0665\u0666\u0667\u0668\u0669"
        }
    },
    "he_IL": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "ur_PK": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "fa_IR": {
        "decimalSeparator": "\u066b",
        "numberDelimiter": "\u066c",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": {
            "digits": "\u06f0\u06f1\u06f2\u06f3\u06f4\u06f5\u06f6\u06f7\u06f8\u06f9"
        }
    },
    "sy_SY": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "yi_DE": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "qc_GT": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "qu_PE": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "ay_BO": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "se_NO": {
        "decimalSeparator": ",",
        "numberDelimiter": "\u00a0",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "ps_AF": {
        "decimalSeparator": "\u066b",
        "numberDelimiter": "\u066c",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": {
            "digits": "\u06f0\u06f1\u06f2\u06f3\u06f4\u06f5\u06f6\u06f7\u06f8\u06f9"
        }
    },
    "tl_ST": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "gx_GR": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "my_MM": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": {
            "digits": "\u1040\u1041\u1042\u1043\u1044\u1045\u1046\u1047\u1048\u1049"
        }
    },
    "qz_MM": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": {
            "digits": "\u1040\u1041\u1042\u1043\u1044\u1045\u1046\u1047\u1048\u1049"
        }
    },
    "or_IN": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 2
        },
        "numberingSystemData": null
    },
    "si_LK": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "hi_FB": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 2
        },
        "numberingSystemData": null
    },
    "eh_IN": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "rw_RW": {
        "decimalSeparator": ",",
        "numberDelimiter": ".",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "ak_GH": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "nd_ZW": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "sn_ZW": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "cb_IQ": {
        "decimalSeparator": "\u066b",
        "numberDelimiter": "\u066c",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": {
            "digits": "\u0660\u0661\u0662\u0663\u0664\u0665\u0666\u0667\u0668\u0669"
        }
    },
    "ha_NG": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "yo_NG": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "ja_KS": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "lg_UG": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "br_FR": {
        "decimalSeparator": ",",
        "numberDelimiter": "\u00a0",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "zz_TR": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "tz_MA": {
        "decimalSeparator": ",",
        "numberDelimiter": "\u00a0",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "co_FR": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "ig_NG": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "as_IN": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 2
        },
        "numberingSystemData": {
            "digits": "\u09e6\u09e7\u09e8\u09e9\u09ea\u09eb\u09ec\u09ed\u09ee\u09ef"
        }
    },
    "am_ET": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "lo_LA": {
        "decimalSeparator": ",",
        "numberDelimiter": ".",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "ny_MW": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "wo_SN": {
        "decimalSeparator": ",",
        "numberDelimiter": ".",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "ff_NG": {
        "decimalSeparator": ",",
        "numberDelimiter": "\u00a0",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "sc_IT": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "ln_CD": {
        "decimalSeparator": ",",
        "numberDelimiter": ".",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "tk_TM": {
        "decimalSeparator": ",",
        "numberDelimiter": "\u00a0",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "sz_PL": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "bp_IN": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "ns_ZA": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "tn_BW": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "st_ZA": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "ts_ZA": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "ss_SZ": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "ks_IN": {
        "decimalSeparator": "\u066b",
        "numberDelimiter": "\u066c",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 2
        },
        "numberingSystemData": {
            "digits": "\u06f0\u06f1\u06f2\u06f3\u06f4\u06f5\u06f6\u06f7\u06f8\u06f9"
        }
    },
    "ve_ZA": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "nr_ZA": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "ik_US": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "fv_NG": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "su_ID": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "om_ET": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "em_ZM": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "qr_GR": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "iu_CA": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "qk_DZ": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "qv_IT": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "qs_DE": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "qb_DE": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "qe_US": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "bv_DE": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    },
    "qt_US": {
        "decimalSeparator": ".",
        "numberDelimiter": ",",
        "minDigitsForThousandsSeparator": 4,
        "standardDecimalPatternInfo": {
            "primaryGroupSize": 3,
            "secondaryGroupSize": 3
        },
        "numberingSystemData": null
    }
};

const NumberFormatConsts {
  get: function(locale) {
    return localeToConfig[locale] || DEFAULT_CONFIG;
  }
};
module.exports = NumberFormatConsts;
