/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<c2bda86292db80a6aebdaed8be671c4f>>
 *
 * Generated by CLDRGenScript
 *
 * @flow
 */
const IntlCLDRNumberType02 = {
  getNumberVariations: function() {
    return [4,24];
  },

  getFallback: function() {
    return 24;
  }

};

module.exports = IntlCLDRNumberType02;
