/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<11f0947e31811d1ddb1a4e8cdc10e69d>>
 *
 * Generated by CLDRGenScript
 *
 * @flow
 */
const IntlCLDRNumberType01 = {
  getNumberVariations: function() {
    return [24];
  },

  getFallback: function() {
    return 24;
  }

};

module.exports = IntlCLDRNumberType01;
