/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<11ab246ae0070c4fd7fa597d19a67a17>>
 *
 * Generated by CLDRGenScript
 *
 * @flow
 */
const IntlCLDRNumberType17 = {
  getNumberVariations: function() {
    return [4,8,24];
  },

  getFallback: function() {
    return 24;
  }

};

module.exports = IntlCLDRNumberType17;
