/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<13b891f843a88e4eeb275377c372f63e>>
 *
 * Generated by CLDRGenScript
 *
 * @flow
 */
const IntlCLDRNumberType45 = {
  getNumberVariations: function() {
    return [4,8,24];
  },

  getFallback: function() {
    return 24;
  }

};

module.exports = IntlCLDRNumberType45;
