/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<c9d7a290321981e24a376fc4fc9e7997>>
 *
 * Generated by CLDRGenScript
 *
 * @flow
 */
const IntlCLDRNumberType32 = {
  getNumberVariations: function() {
    return [4,8,20,12,24];
  },

  getFallback: function() {
    return 24;
  }

};

module.exports = IntlCLDRNumberType32;
