/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<3545059ac35ed29961af5b4d4ab5487b>>
 *
 * Generated by CLDRGenScript
 *
 * @flow
 */
const IntlCLDRNumberType31 = {
  getNumberVariations: function() {
    return [4,8,20,12,24];
  },

  getFallback: function() {
    return 24;
  }

};

module.exports = IntlCLDRNumberType31;
