/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<3d9abcbb996710cc71b3d9f2ce2c4fd7>>
 *
 * Generated by CLDRGenScript
 *
 * @flow
 */
const IntlCLDRNumberType43 = {
  getNumberVariations: function() {
    return [4,20,12,24];
  },

  getFallback: function() {
    return 12;
  }

};

module.exports = IntlCLDRNumberType43;
