/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<35080e88b079a31833b935a3d1f0bc74>>
 *
 * Generated by CLDRGenScript
 *
 * @flow
 */
const IntlCLDRNumberType20 = {
  getNumberVariations: function() {
    return [4,20,24];
  },

  getFallback: function() {
    return 24;
  }

};

module.exports = IntlCLDRNumberType20;
