/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<811463e22056238d3a06c3631c4388e1>>
 *
 * Generated by CLDRGenScript
 *
 * @flow
 */
const IntlCLDRNumberType06 = {
  getNumberVariations: function() {
    return [4,24];
  },

  getFallback: function() {
    return 24;
  }

};

module.exports = IntlCLDRNumberType06;
