/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<ae99ea93b5448f06fd91485ffc0555e7>>
 *
 * Generated by CLDRGenScript
 *
 * @flow
 */
const IntlCLDRNumberType25 = {
  getNumberVariations: function() {
    return [4,20,12,24];
  },

  getFallback: function() {
    return 24;
  }

};

module.exports = IntlCLDRNumberType25;
