/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<39f5b8e25903fed1b655a156de5d7293>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow
 */
const IntlCLDRNumberType28 = {
  getNumberVariations: function() {
    return [4,20,12,24];
  },

  getFallback: function() {
    return 24;
  }

};

module.exports = IntlCLDRNumberType28;
