/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<20f6a13ebc9782907cb5bd6b4dc9cea1>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType16 = {
  getNumberVariations() /*: $ReadOnlyArray<number> */ {
    return [16,4,24];
  },

  getFallback() /*: number */ {
    return 24;
  }
};

module.exports = IntlCLDRNumberType16;
