/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<37b7afe7f6dd2dbb4e124ba4fff0da21>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType07 = {
  getNumberVariations() /*: $ReadOnlyArray<number> */ {
    return [4,24];
  },

  getFallback() /*: number */ {
    return 24;
  }
};

module.exports = IntlCLDRNumberType07;
