/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<a4c45bc1f8cd55b6853ca90a0623ca69>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType25 = {
  getNumberVariations() /*: $ReadOnlyArray<number> */ {
    return [4,20,12,24];
  },

  getFallback() /*: number */ {
    return 24;
  }
};

module.exports = IntlCLDRNumberType25;
