/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<9f62736b0017f9f7ebba9f351933d751>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow
 */
const IntlCLDRNumberType40 = {
  getNumberVariations: function() {
    return [4,8,24];
  },

  getFallback: function() {
    return 24;
  }

};

module.exports = IntlCLDRNumberType40;
