/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<14fda798177e151dd0599dfbf3a75792>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow
 */
const IntlCLDRNumberType17 = {
  getNumberVariations: function() {
    return [4,8,24];
  },

  getFallback: function() {
    return 24;
  }

};

module.exports = IntlCLDRNumberType17;
