/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<52404e5fb8b233c3bfde2dd6bbadd36a>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType01 = {
  getNumberVariations() /*: $ReadOnlyArray<number> */ {
    return [24];
  },

  getFallback() /*: number */ {
    return 24;
  }
};

module.exports = IntlCLDRNumberType01;
