/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<5367c46afc870cdf55a66bb87e34c913>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType27 = {
  getNumberVariations() /*: $ReadOnlyArray<number> */ {
    return [4,20,12,24];
  },

  getFallback() /*: number */ {
    return 12;
  }
};

module.exports = IntlCLDRNumberType27;
