/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<cdd3b6a49f5723e514a8307dba8ac639>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType29 = {
  getNumberVariations() /*: $ReadOnlyArray<number> */ {
    return [4,20,12,24];
  },

  getFallback() /*: number */ {
    return 24;
  }
};

module.exports = IntlCLDRNumberType29;
