/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<0e5a32c8014a3308a8e845ab941b9ee9>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType33 = {
  getNumberVariations() /*: $ReadOnlyArray<number> */ {
    return [4,8,20,12,24];
  },

  getFallback() /*: number */ {
    return 24;
  }
};

module.exports = IntlCLDRNumberType33;
