/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<f8e73b407f60c5993040e66a79d71631>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType30 = {
  getNumberVariations() /*: $ReadOnlyArray<number> */ {
    return [4,20,12,24];
  },

  getFallback() /*: number */ {
    return 12;
  }
};

module.exports = IntlCLDRNumberType30;
