/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<3fff8e5b05011d47ecd50f1c7c7d57b2>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType42 = {
  getNumberVariations() /*: $ReadOnlyArray<number> */ {
    return [24];
  },

  getFallback() /*: number */ {
    return 24;
  }
};

module.exports = IntlCLDRNumberType42;
