/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<c2b0ace89c0826b1a12106fa96c5cdf2>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType21 = {
  getNumberVariations() /*: $ReadOnlyArray<number> */ {
    return [4,8,20,24];
  },

  getFallback() /*: number */ {
    return 24;
  }
};

module.exports = IntlCLDRNumberType21;
