/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<51da407c4822182c5f1b6c650adb38f0>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow
 */
const IntlCLDRNumberType23 = {
  getNumberVariations: function() {
    return [4,8,20,24];
  },

  getFallback: function() {
    return 24;
  }

};

module.exports = IntlCLDRNumberType23;
