/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<ebf8983ffed3e81cb5e3fe71b8cbcfe9>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType20 = {
  getNumberVariations() /*: $ReadOnlyArray<number> */ {
    return [4,20,24];
  },

  getFallback() /*: number */ {
    return 24;
  }
};

module.exports = IntlCLDRNumberType20;
