/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<2f72c8cfe0f25ee46f67aac0336b295d>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType22 = {
  getNumberVariations() /*: $ReadOnlyArray<number> */ {
    return [4,8,20,24];
  },

  getFallback() /*: number */ {
    return 24;
  }
};

module.exports = IntlCLDRNumberType22;
