/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow strict
 */

'use strict';

const IntlVariations = require('IntlVariations');

const IntlCLDRNumberType39 = {
  getVariation(n /*: number */) /*: $Values<typeof IntlVariations> */ {
    return IntlVariations.NUMBER_OTHER;
  }
};

module.exports = IntlCLDRNumberType39;
