/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<67c659168c4ce8857e4228dbe82c94f2>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow
 */
const IntlVariations = require('IntlVariations');
const IntlCLDRNumberType39 = {
  getVariation(n: number): number {
    return IntlVariations.NUMBER_OTHER;
  }
};

module.exports = IntlCLDRNumberType39;
