/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<e20548e66f04dfd922d086ba1c15b3b6>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow
 */
const IntlVariations = require('IntlVariations');
const IntlCLDRNumberType42 = {
  getVariation(n: number): number {
    return IntlVariations.NUMBER_OTHER;
  }
};

module.exports = IntlCLDRNumberType42;
