/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<81b8897581abde9aeb7c2c4add9118b3>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow strict
 */

'use strict';

const IntlVariations = require('IntlVariations');

const IntlCLDRNumberType31 = {
  getVariation(n /*: number */) /*: $Values<typeof IntlVariations> */ {
    if (n % 10 === 1 && (n % 100 !== 11 && n % 100 !== 71 && n % 100 !== 91)) {
      return IntlVariations.NUMBER_ONE;
    } else if (n % 10 === 2 && (n % 100 !== 12 && n % 100 !== 72 && n % 100 !== 92)) {
      return IntlVariations.NUMBER_TWO;
    } else if ((n % 10 >= 3 && n % 10 <= 4 || n % 10 === 9) && ((n % 100 < 10 || n % 100 > 19) && (n % 100 < 70 || n % 100 > 79) && (n % 100 < 90 || n % 100 > 99))) {
      return IntlVariations.NUMBER_FEW;
    } else if (n !== 0 && n % 1000000 === 0) {
      return IntlVariations.NUMBER_MANY;
    } else {
      return IntlVariations.NUMBER_OTHER;
    }
  }
};

module.exports = IntlCLDRNumberType31;
