/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<7dc3715f318758ccdf179f9ed7c84c93>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow strict
 */

'use strict';

const IntlVariations = require('IntlVariations');

const IntlCLDRNumberType01 = {
  getVariation(n /*: number */) /*: $Values<typeof IntlVariations> */ {
    return IntlVariations.NUMBER_OTHER;
  }
};

module.exports = IntlCLDRNumberType01;
