/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<07f60df506a466e7c0096c389714fad4>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow strict
 */

'use strict';

const IntlVariations = require('IntlVariations');

const IntlCLDRNumberType42 = {
  getVariation(n /*: number */) /*: $Values<typeof IntlVariations> */ {
    return IntlVariations.NUMBER_OTHER;
  }
};

module.exports = IntlCLDRNumberType42;
