/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated SignedSource<<4a0a3f917f0b28cf1c35e1298beea247>>
 *
 * Generated by LanguageCLDRGenScript
 * @codegen-command: flib/intern/scripts/intl/cldr/gencode_all_plurals.sh
 *
 * @flow strict
 */

'use strict';

const IntlVariations = require('IntlVariations');

const IntlCLDRNumberType39 = {
  getVariation(n: number): $Values<typeof IntlVariations> {
    return IntlVariations.NUMBER_OTHER;
  }
};

module.exports = IntlCLDRNumberType39;
