/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<d958b3088e6e44066fb9ea79eee06e23>>
 *
 * Generated by LanguageCLDRGenScript
 * @codegen-command: flib/intern/scripts/intl/cldr/gencode_all_plurals.sh
 *
 * @flow strict
 */

'use strict';

const IntlVariations = require('IntlVariations');

const IntlCLDRNumberType01 = {
  getVariation(n: number): $Values<typeof IntlVariations> {
    return IntlVariations.NUMBER_OTHER;
  }
};

module.exports = IntlCLDRNumberType01;
