/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<a208f58c7ecee3fb65a16a7536a5c4f3>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow strict
 */

'use strict';

const IntlVariations = require('IntlVariations');

const IntlCLDRNumberType01 = {
  getVariation(n: number): $Values<typeof IntlVariations> {
    return IntlVariations.NUMBER_OTHER;
  }
};

module.exports = IntlCLDRNumberType01;
