/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<31776c687d0abd7896ee9c37040e7655>>
 *
 * Generated by LanguageCLDRGenScript
 * @codegen-command: flib/intern/scripts/intl/cldr/gencode_all_plurals.sh
 *
 * @flow strict
 */

'use strict';

const IntlVariations = require('IntlVariations');

const IntlCLDRNumberType13 = {
  getVariation(n: number): $Values<typeof IntlVariations> {
    if ((n === 1 || n === 2 || n === 3) || (n % 10 !== 4 && n % 10 !== 6 && n % 10 !== 9)) {
      return IntlVariations.NUMBER_ONE;
    } else {
      return IntlVariations.NUMBER_OTHER;
    }
  }
};

module.exports = IntlCLDRNumberType13;
