/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<cdf20aef39bb9c8f6cd9d21b845ea367>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow strict
 */

'use strict';

const IntlVariations = require('IntlVariations');

const IntlCLDRNumberType39 = {
  getVariation(n: number): $Values<typeof IntlVariations> {
    return IntlVariations.NUMBER_OTHER;
  }
};

module.exports = IntlCLDRNumberType39;
