/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<69bfd30a741fe4821132bd4cb031c9d6>>
 *
 * Generated by LanguageCLDRGenScript
 * @codegen-command: flib/intern/scripts/intl/cldr/gencode_all_plurals.sh
 *
 * @flow strict
 */

'use strict';

const IntlVariations = require('IntlVariations');

const IntlCLDRNumberType39 = {
  getVariation(n: number): $Values<typeof IntlVariations> {
    return IntlVariations.NUMBER_OTHER;
  }
};

module.exports = IntlCLDRNumberType39;
