/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<98ada37e96f2f4ab679ce69edd177b3e>>
 *
 * Generated by LanguageCLDRGenScript
 * @codegen-command: flib/intern/scripts/intl/cldr/gencode_all_plurals.sh
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType21 = {
  getNumberVariations(): $ReadOnlyArray<number> {
    return [4,8,20,24];
  },

  getFallback(): number {
    return 24;
  }
};

module.exports = IntlCLDRNumberType21;
