/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<530c607f2265f799d125d8ef1a4f6771>>
 *
 * Generated by LanguageCLDRGenScript
 * @codegen-command: flib/intern/scripts/intl/cldr/gencode_all_plurals.sh
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType28 = {
  getNumberVariations(): $ReadOnlyArray<number> {
    return [4,20,12,24];
  },

  getFallback(): number {
    return 24;
  }
};

module.exports = IntlCLDRNumberType28;
