/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<2b23642966437de6670b38c64d575c27>>
 *
 * Generated by LanguageCLDRGenScript
 * @codegen-command: flib/intern/scripts/intl/cldr/gencode_all_plurals.sh
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType31 = {
  getNumberVariations(): $ReadOnlyArray<number> {
    return [4,8,20,12,24];
  },

  getFallback(): number {
    return 24;
  }
};

module.exports = IntlCLDRNumberType31;
