/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<9788a7fb7992ea97e6bf7723c5843627>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType19 = {
  getNumberVariations(): $ReadOnlyArray<number> {
    return [4,20,24];
  },

  getFallback(): number {
    return 24;
  }
};

module.exports = IntlCLDRNumberType19;
