/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<f1f2d5bfe48635eee44f27d765ecfa50>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType01 = {
  getNumberVariations(): $ReadOnlyArray<number> {
    return [24];
  },

  getFallback(): number {
    return 24;
  }
};

module.exports = IntlCLDRNumberType01;
