/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<089d66e4e3d48aa3eb23c1b32ad8b98e>>
 *
 * Generated by LanguageCLDRGenScript
 * @codegen-command: flib/intern/scripts/intl/cldr/gencode_all_plurals.sh
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType17 = {
  getNumberVariations(): $ReadOnlyArray<number> {
    return [4,8,24];
  },

  getFallback(): number {
    return 24;
  }
};

module.exports = IntlCLDRNumberType17;
