/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<3fabe90fdede45675e668cbf5f90c105>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType09 = {
  getNumberVariations(): $ReadOnlyArray<number> {
    return [4,24];
  },

  getFallback(): number {
    return 24;
  }
};

module.exports = IntlCLDRNumberType09;
