/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<58a3b2aff3a2d2226641332dca9bfcb1>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType44 = {
  getNumberVariations() /*: $ReadOnlyArray<number> */ {
    return [4,24];
  },

  getFallback() /*: number */ {
    return 24;
  }
};

module.exports = IntlCLDRNumberType44;
