/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<1b2aa1537c6d3df4f858815b76ae1163>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType28 = {
  getNumberVariations() /*: $ReadOnlyArray<number> */ {
    return [4,20,12,24];
  },

  getFallback() /*: number */ {
    return 24;
  }
};

module.exports = IntlCLDRNumberType28;
