/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<9cb30a4634cec5e89b123fbe539ac834>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType20 = {
  getNumberVariations(): $ReadOnlyArray<number> {
    return [4,20,24];
  },

  getFallback(): number {
    return 24;
  }
};

module.exports = IntlCLDRNumberType20;
