/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<be5c847201c09660b100fd3f2ab0bf27>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType30 = {
  getNumberVariations(): $ReadOnlyArray<number> {
    return [4,20,12,24];
  },

  getFallback(): number {
    return 12;
  }
};

module.exports = IntlCLDRNumberType30;
