/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<337cabc4e657af688b1a861eabbc77c6>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType04 = {
  getNumberVariations() /*: $ReadOnlyArray<number> */ {
    return [4,24];
  },

  getFallback() /*: number */ {
    return 24;
  }
};

module.exports = IntlCLDRNumberType04;
