/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<971fcafabdab7e9045a0acb402e2d3d0>>
 *
 * Generated by LanguageCLDRGenScript
 * @codegen-command: flib/intern/scripts/intl/cldr/gencode_all_plurals.sh
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType46 = {
  getNumberVariations(): $ReadOnlyArray<number> {
    return [4,20,24];
  },

  getFallback(): number {
    return 24;
  }
};

module.exports = IntlCLDRNumberType46;
