/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<307eb68f1ea1e4e808cc0d3a66cf0e17>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType39 = {
  getNumberVariations(): $ReadOnlyArray<number> {
    return [24];
  },

  getFallback(): number {
    return 24;
  }
};

module.exports = IntlCLDRNumberType39;
