/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<caf2260f2dd0a7df3c571fb29f2b4256>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType17 = {
  getNumberVariations(): $ReadOnlyArray<number> {
    return [4,8,24];
  },

  getFallback(): number {
    return 24;
  }
};

module.exports = IntlCLDRNumberType17;
