/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<41731ddedcb45b09aabb0a6753bc04b5>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType41 = {
  getNumberVariations(): $ReadOnlyArray<number> {
    return [4,24];
  },

  getFallback(): number {
    return 24;
  }
};

module.exports = IntlCLDRNumberType41;
