/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<c537d1a16ca4a525e817489276c33c84>>
 *
 * Generated by LanguageCLDRGenScript
 * @codegen-command: flib/intern/scripts/intl/cldr/gencode_all_plurals.sh
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType47 = {
  getNumberVariations(): $ReadOnlyArray<number> {
    return [16,4,24];
  },

  getFallback(): number {
    return 24;
  }
};

module.exports = IntlCLDRNumberType47;
