/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<cc8f7d96aaeef2a01a9092f60e2845c6>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType45 = {
  getNumberVariations(): $ReadOnlyArray<number> {
    return [4,8,24];
  },

  getFallback(): number {
    return 24;
  }
};

module.exports = IntlCLDRNumberType45;
