/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<3743121e76c78806c7a0e7e7d74223d4>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType23 = {
  getNumberVariations(): $ReadOnlyArray<number> {
    return [4,8,20,24];
  },

  getFallback(): number {
    return 24;
  }
};

module.exports = IntlCLDRNumberType23;
