/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<c99f4883d244722ef11dfc511c7b4675>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType33 = {
  getNumberVariations(): $ReadOnlyArray<number> {
    return [4,8,20,12,24];
  },

  getFallback(): number {
    return 24;
  }
};

module.exports = IntlCLDRNumberType33;
