/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<902fd702e8021cf8ec51ae1b64368671>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType40 = {
  getNumberVariations(): $ReadOnlyArray<number> {
    return [4,8,24];
  },

  getFallback(): number {
    return 24;
  }
};

module.exports = IntlCLDRNumberType40;
