/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<f3bae893e3f57be6ed5d56839b5d908f>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType27 = {
  getNumberVariations(): $ReadOnlyArray<number> {
    return [4,20,12,24];
  },

  getFallback(): number {
    return 12;
  }
};

module.exports = IntlCLDRNumberType27;
