/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<dc098390a80c8954bf4bfb9bd7261c9a>>
 *
 * Generated by LanguageCLDRGenScript
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType42 = {
  getNumberVariations(): $ReadOnlyArray<number> {
    return [24];
  },

  getFallback(): number {
    return 24;
  }
};

module.exports = IntlCLDRNumberType42;
