/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<f417749cb944f5f406261d2d71602a32>>
 *
 * Generated by LanguageCLDRGenScript
 * @codegen-command: flib/intern/scripts/intl/cldr/gencode_all_plurals.sh
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType41 = {
  getNumberVariations(): $ReadOnlyArray<number> {
    return [4,24];
  },

  getFallback(): number {
    return 24;
  }
};

module.exports = IntlCLDRNumberType41;
