/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @generated SignedSource<<b622d82e36aec7166af6b0c782017896>>
 *
 * Generated by LanguageCLDRGenScript
 * @codegen-command: flib/intern/scripts/intl/cldr/gencode_all_plurals.sh
 *
 * @flow strict
 */

'use strict';

const IntlCLDRNumberType37 = {
  getNumberVariations(): $ReadOnlyArray<number> {
    return [4,24];
  },

  getFallback(): number {
    return 24;
  }
};

module.exports = IntlCLDRNumberType37;
